import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarWrapper from "@/components/shared/NavbarWrapper";
import Footer from "@/components/shared/Footeer";
import Toast from "@/components/shared/Toast";
import { WorkoutProvider } from "@/context/WorkoutContext";

// const geistSans = Geist({
//     variable: "--font-geist-sans",
//     subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//     variable: "--font-geist-mono",
//     subsets: ["latin"],
// });

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export const metadata: Metadata = {
    title: "FITLOG - Workout Library",
    description: "Train hard, log honest.",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className="bg-[#0d0e12] text-white antialiased">
                <WorkoutProvider>
                    <NavbarWrapper />
                    {children}
                    <Footer />
                    <Toast />
                </WorkoutProvider>
            </body>
        </html>
    );
}
